predicates:
  admission:
    code: { regex: "ICU_ADMISSION//.*" }
  discharge:
    code: { regex: "ICU_DISCHARGE//.*" }
  death:
    code: { regex: "DEATH" }
  discharge_or_death:
    expr: or(discharge, death)

trigger: admission

windows:
  input:
    start: trigger
    end: start + 24h
    start_inclusive: True
    end_inclusive: True
    index_timestamp: end
  gap:
    start: trigger
    end: start + 24h
    start_inclusive: False
    end_inclusive: True
    has:
      admission: (None, 0)
      discharge: (None, 0)
      death: (None, 0)
  target:
    start: gap.end
    end: start -> discharge_or_death
    start_inclusive: False
    end_inclusive: True
    label: death
