predicates:
  icu_admission:
    code:
      regex: "ICU_ADMISSION//.*"
  icu_discharge:
    code:
      regex: "ICU_DISCHARGE//.*"
  death:
    code:
      regex: "DEATH"
  icu_discharge_or_death:
    expr: "or(icu_discharge, death)"

trigger: icu_admission

windows:
  input:
    start: trigger
    end: start + 24h
    start_inclusive: True
    end_inclusive: True
    index_timestamp: end
  gap:
    start: trigger
    end: start + 24h
    start_inclusive: False
    end_inclusive: True
    has:
      icu_admission: (None, 0)
      icu_discharge: (None, 0)
      death: (None, 0)
  target:
    start: gap.end
    end: start + 7d
    start_inclusive: False
    end_inclusive: True
    label: icu_discharge_or_death